// Generated by Blume. Do not edit.
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { withIncludeRefresh } from "blume/astro";
import { pageCollectionSchema } from "blume/core/schema.ts";

// withIncludeRefresh keeps <include>-bearing pages fresh: plain .md entries
// are rendered at sync time and digest-cached on the page file alone, so a
// partial edit (or a warm-cache rebuild after one) would serve stale HTML.
//
// pageCollectionSchema is the scan's page front-matter schema, so entry.data
// is typed and normalized the same way; it passes custom keys through and
// falls back to defaults for a page the scan already dropped as invalid.
const docs = defineCollection({
  loader: withIncludeRefresh(glob({
    pattern: ["**/*.{md,mdx}","!**/_*","!**/.*","!**/.blume-verify/**","!**/.cache/**","!**/.git/**","!**/.next/**","!**/.turbo/**","!**/.vercel/**","!**/dist/**","!**/node_modules/**"],
    base: "file:///C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/docs",
    generateId: ({ entry }) => entry,
  }), "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/includes.json"),
  schema: pageCollectionSchema,
});

export const collections = { docs };
