// Generated by Blume. Do not edit.
import { navigationResponse } from "blume/ai/api/handlers.ts";
import data from "blume:mcp-data";

export const prerender = true;

export function GET() {
  return navigationResponse(data);
}
