// Generated by Blume. Do not edit; this file is recreated on each run.
import { availableParallelism } from "node:os";
import { defineConfig, fontProviders } from "astro/config";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";
import { blumeMarkdownProcessor, blumeMdxProcessor, blumeShikiTransformers, blumeTwoslashTransformer } from "blume/markdown";
import { blumeIntegration, includeHmrPlugin, prerenderDepsPlugin, runtimeModulesPlugin } from "blume/astro";

export default defineConfig({
  root: "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume",
  srcDir: "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src",
  outDir: "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/dist",
  publicDir: "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/public",
  cacheDir: "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/.cache/astro",
  output: "static",
  site: "http://localhost:4321",
  fonts: [{ provider: fontProviders.google(), name: "Inter", cssVariable: "--blume-ff-inter", weights: ["400 700"], subsets: ["latin"], fallbacks: ["ui-sans-serif","system-ui","sans-serif"] }, { provider: fontProviders.google(), name: "IBM Plex Mono", cssVariable: "--blume-ff-ibm-plex-mono", weights: [400,500,600], subsets: ["latin"], fallbacks: ["ui-monospace","SF Mono","Menlo","monospace"] }],
  integrations: [mdx({ processor: blumeMdxProcessor({"basePath":"","codeThemes":{"dark":"github-dark","light":"github-light"},"contentRoot":"C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/docs","deployBase":"","headingAnchors":true}) }), blumeIntegration({"pages":[]})],
  markdown: {
    processor: blumeMarkdownProcessor({"basePath":"","codeThemes":{"dark":"github-dark","light":"github-light"},"contentRoot":"C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/docs","deployBase":"","headingAnchors":true}),
    shikiConfig: {
      themes: {
        light: "github-light",
        dark: "github-dark",
      },
      defaultColor: false,
      transformers: [blumeTwoslashTransformer(), ...blumeShikiTransformers({"icons":true})],
    },
  },
  devToolbar: { enabled: false },
  // One canonical URL per page: canonicals, the sitemap, and hreflang all use
  // the slashless form, so the slashed spelling is not a second address. Astro
  // applies this itself — its dev server answers a slashed URL with a 404 that
  // names the setting, an on-demand route redirects — and the Vercel adapter
  // turns it into the platform's 308 route, so the Build Output config needs
  // no hand-spliced redirect (see deploy/vercel-negotiation.ts). Static hosts
  // serve the `index.html` directory layout as they always did.
  trailingSlash: "never",
  // The layouts render Astro's <ClientRouter />, and its in-place swaps read
  // from the prefetch cache — fetching every link on hover/viewport hides the
  // request latency behind the user's intent, so most navigations swap
  // instantly.
  prefetch: { prefetchAll: true },
  // Prerender several pages at once. Rendering is single-threaded, but a
  // page's OG card renders on a native thread and its HTML is written
  // asynchronously, so the main thread would otherwise idle behind each
  // page's off-thread work. Capped at 8: the gain flattens there and beyond it
  // the overlap only adds memory.
  build: { concurrency: Math.min(8, availableParallelism()) },
  vite: {
    cacheDir: "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/.cache/vite",
    plugins: [runtimeModulesPlugin(), tailwindcss(), includeHmrPlugin("C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/includes.json"), prerenderDepsPlugin()],
    // Everything hydration can reach must be part of the dev dep optimizer's
    // FIRST run. The Vite root is the generated runtime, so user pages,
    // islands, and aliased components live outside it and are only crawled
    // when first requested — and `react/compiler-runtime` is Babel-injected,
    // so no source scan can ever see it. A dependency discovered after
    // hydration begins triggers a mid-session re-optimization whose new
    // generation imports React through new `?v=` URLs; the browser then
    // evaluates a second React copy and every island tears down with
    // "Invalid hook call" (#157). `entries` points the startup scanner at
    // the user's files (the scanner follows their imports, so their deps land
    // in the initial optimization); the compiler runtime rides the include
    // list because only the transform pipeline knows it exists.
    //
    // The mermaid/epub includes fix CJS interop instead: both lazy client-side
    // imports land on CJS/UMD files (mermaid statically imports dayjs as CJS,
    // epub-gen-memory's browser bundle is a browserified UMD) that break when
    // served as raw ESM — mermaid throws on load and the EPUB export throws
    // `epub is not a function`. They resolve through the `blume` package
    // (they aren't direct deps of the generated project), so the nested
    // `blume > x` form is required, and epub-gen-memory must name the
    // `/bundle` subpath that is actually imported: optimizing the package
    // root leaves that entry out. Production (Rollup) already handles the
    // interop, so all of this only affects dev.
    optimizeDeps: {
      entries: ["C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/islands/**/*.{jsx,svelte,tsx,vue}"],
      include: [],
    },
    // Blume's render-time deps are forced external on both build environments so
    // native bindings resolve at runtime and isolated linkers don't bundle
    // symlinked store copies (which would surface their children as unresolvable
    // imports). See RENDER_EXTERNAL_DEPS / prerenderDepsPlugin.
    //
    // The SSR externals go through the legacy `ssr.external` key rather than
    // `environments.ssr`: defining a user-owned `environments.ssr` block
    // collides with the internal environment Astro 7 builds the server under and
    // detaches the adapter's server entrypoint from the rolldown input, so the
    // SSR entry is emitted as `index.mjs` instead of the `entry.mjs` the
    // Vercel adapter's `astro:build:done` hook then fails to find. `prerender`
    // is Astro-only and has no legacy equivalent, so it stays under `environments`.
    ssr: { external: ["@astrojs/markdown-satteri","@pierre/diffs","@shikijs/transformers","@takumi-rs/core","@takumi-rs/helpers","@takumi-rs/wasm","github-slugger","katex","shiki","simple-icons","takumi-js","takumi-js/helpers","zod"] },
    environments: {
      prerender: { resolve: { external: ["@astrojs/markdown-satteri","@pierre/diffs","@shikijs/transformers","@takumi-rs/core","@takumi-rs/helpers","@takumi-rs/wasm","github-slugger","katex","shiki","simple-icons","takumi-js","takumi-js/helpers","zod"] } },
    },
    resolve: {
      alias: {
        "blume:ask": "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/Ask.astro",
        "blume:examples": "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/examples.ts",
        "blume:examples-theme": "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/examples.css",
        "blume:features": "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/features.ts",
        "blume:search-client": "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/search-client.ts",
        "blume:theme": "C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/.blume/src/generated/app.css",
      },
    },
    server: {
      fs: {
        allow: ["C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation"],
      },
    },
  },
});
