// Generated by Blume. Do not edit.
import { pageParams, pageResponse } from "blume/ai/api/handlers.ts";
import data from "blume:mcp-data";

export const prerender = true;

export function getStaticPaths() {
  return pageParams(data);
}

export function GET({ props }: { props: { route: string } }) {
  return pageResponse(data, props.route);
}
