// Generated by Blume. Do not edit.
import { cachedOgImage } from "blume/og";
import type { OgCache, OgFont, OgFontFamilies } from "blume/og";
import data from "blume:data";

export const prerender = true;

// Custom (non-content) pages opted into a generated card, baked in at build.
// The annotation keeps the empty-array case from being an implicit any[]
// (ts(7034)) under a strict tsconfig.
const customRoutes: { slug: string; title: string }[] = [];

// Card fonts, resolved at generation time (explicit seo.og.fonts, or derived
// from theme.fonts). Local entries carry absolute build-machine paths, which
// is why they are baked into this build-only endpoint instead of the runtime
// data that pages serialize into HTML.
const fonts: OgFont[] = [];
const families: OgFontFamilies | undefined = undefined;

// Rendered cards are kept on disk between builds, keyed by everything that
// decides their pixels, so a rebuild renders only the cards whose title,
// description, branding, or fonts changed. The directory is a build-machine
// path, baked in for the same reason as the local font paths above.
const cache: OgCache | undefined = {"dir":"C:/Users/gsera/OneDrive/Desktop/NFDI4Memory/WP_HTML_Dokumentation/node_modules/.cache/blume/og","version":"1.7.0"};

// A page's own description (its `seo.description`, else `description`) is
// the card subtitle, so the image says what the page's og:description says.
// Pages without one fall back to the site-wide subtitle at render time.
// `seo.og.description: false` hides the subtitle on every card, page text
// included, which is what switches this off.
const pageDescriptions = true;

interface CardProps {
  title: string;
  description: string | null;
}

export function getStaticPaths() {
  const seen = new Set<string>();
  const paths: { params: { slug: string }; props: CardProps }[] = [];
  const add = (slug: string, title: string, description: string | null) => {
    if (seen.has(slug)) {
      return;
    }
    seen.add(slug);
    paths.push({
      params: { slug },
      props: { title, description: pageDescriptions ? description : null },
    });
  };
  // A custom page wins over a content route sharing its path, so add it first.
  // Its description is unknown at generate time, so it takes the site subtitle.
  for (const route of customRoutes) {
    add(route.slug, route.title, null);
  }
  for (const route of data.routes) {
    add(
      route.path === "/" ? "index" : route.path.slice(1),
      route.title,
      route.description
    );
  }
  return paths;
}

// Footer branding shared by every card. The slug comes from the configured
// repo rather than the URL, so an Enterprise host reads the same as github.com;
// the site text (host plus deployment base) is resolved at generate time.
const repoSlug = data.config.github
  ? `${data.config.github.owner}/${data.config.github.repo}`
  : undefined;

export async function GET({ props }: { props: CardProps }) {
  const png = await cachedOgImage(cache, {
    accent: data.config.og.palette?.accent ?? data.config.theme.accent.light,
    brand: data.config.title,
    description: props.description ?? data.config.og.description,
    families,
    fonts,
    logo: data.config.og.logo,
    palette: data.config.og.palette,
    repo: repoSlug,
    site: data.config.og.site,
    title: props.title,
  });
  return new Response(new Uint8Array(png), {
    headers: {
      "Cache-Control": "public, max-age=31536000, immutable",
      "Content-Type": "image/png",
    },
  });
}
