// Generated by Blume. Do not edit. Override by adding `pages/404.astro`.
import { withBase } from "blume/components/islands/base-path.ts";
import { absoluteUrl } from "blume/core/site-url.ts";
import data from "blume:data";

export const prerender = true;

const nf = data.ui.notFound;

// Absolute for internal routes when the site is known; an external tab href
// passes through untouched.
const href = (path: string): string => {
  const based = withBase(path);
  return data.config.site && based.startsWith("/") && !based.startsWith("//")
    ? absoluteUrl(data.config.site, based)
    : based;
};

// The recovery set of 404.astro: home, every top-level section (a tab links to
// its resolved target), then the machine-readable indexes that exist.
const links = [
  { href: href("/"), label: nf.home },
  ...data.navigation.tabs.map((tab) => ({
    href: href(tab.href ?? tab.path),
    label: tab.label,
  })),
  ...(data.config.discovery.sitemap
    ? [{ href: href("/sitemap.xml"), label: nf.sitemap }]
    : []),
  ...(data.config.discovery.llmsTxt
    ? [{ href: href("/llms.txt"), label: nf.llms }]
    : []),
  ...(data.config.discovery.api
    ? [{ href: href("/openapi.json"), label: nf.api }]
    : []),
];

const body = [
  "# " + nf.title,
  "",
  nf.description,
  "",
  "## " + nf.suggestions,
  "",
  ...links.map((link) => "- [" + link.label + "](" + link.href + ")"),
  "",
].join("\n");

export function GET() {
  return new Response(body, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      // ~4 characters per token; keep in sync with markdownTokenCount.
      "x-markdown-tokens": String(Math.ceil(body.length / 4)),
    },
  });
}
