// Generated by Blume. Do not edit. Override by adding `pages/404.astro`.
import { problem } from "blume/ai/api/problem.ts";
import { withBase } from "blume/components/islands/base-path.ts";
import { absoluteUrl } from "blume/core/site-url.ts";
import data from "blume:data";

export const prerender = true;

const nf = data.ui.notFound;

// Absolute for internal routes when the site is known; an external tab href
// passes through untouched.
const href = (path: string): string => {
  const based = withBase(path);
  return data.config.site && based.startsWith("/") && !based.startsWith("//")
    ? absoluteUrl(data.config.site, based)
    : based;
};

// The recovery set of 404.astro: home, every top-level section (a tab links to
// its resolved target), then the machine-readable indexes that exist.
const links = [
  { href: href("/"), label: nf.home },
  ...data.navigation.tabs.map((tab) => ({
    href: href(tab.href ?? tab.path),
    label: tab.label,
  })),
  ...(data.config.discovery.sitemap
    ? [{ href: href("/sitemap.xml"), label: nf.sitemap }]
    : []),
  ...(data.config.discovery.llmsTxt
    ? [{ href: href("/llms.txt"), label: nf.llms }]
    : []),
  ...(data.config.discovery.api
    ? [{ href: href("/openapi.json"), label: nf.api }]
    : []),
];

const body = problem({
  code: "PAGE_NOT_FOUND",
  detail: nf.description,
  links,
  resolution: nf.suggestions + ": " + links.map((link) => link.href).join(", "),
  status: 404,
  title: nf.title,
});

export function GET() {
  return new Response(JSON.stringify(body, null, 2) + "\n", {
    headers: { "Content-Type": "application/problem+json; charset=utf-8" },
  });
}
