// Generated by Blume. Do not edit.
import documents from "blume:search-index";

export const prerender = true;

export function GET() {
  return new Response(JSON.stringify(documents), {
    headers: { "Content-Type": "application/json" },
  });
}
